#' @title Deconvoluting Wastewater Data to Incidence
#' @description Function estimates incidence from smoothed data
#'
#' @param d Data frame. Wastewater dataframe. Must include at least `date` and
#'  `obs` columns.
#' @param fec List. Parameters for a single fecal shedding distribution, as generated by [sample_a_dist()].
#' @inheritParams estimate_R_ww
#' @template param-silent
#'
#' @importFrom rlang .data
#'
#' @return Data frame with deconvoluted incidence
deconv_ww_inc <- function(d, fec, scaling.factor, silent){

  d$obs_scal = d$obs * scaling.factor

  start_date = as.Date(dplyr::first(d$date))

  f = get_discrete_dist(fec)

  inc = deconvolution_RL(observed = d$obs_scal,
                         times = d$t,
                         p_delay = f,
                         verbose = !silent) %>%
    # Forces incidence to be a positive integer:
    dplyr::mutate(
      inc.deconvol = as.integer(ifelse(
        .data$RL_result>0, .data$RL_result, 0))) %>%
    # Retreive corresponding dates:
    dplyr::rename(t = .data$time) %>%
    dplyr::filter(t > 0) %>%
    dplyr::mutate(date = start_date + t)

  res = list(
    inc         = inc,
    ww.smooth   = d,
    fec         = fec,
    scaling.factor = scaling.factor
  )
  return(res)
}
